export const champions = [
  {
    stat: {
      Cost: "4",
      Health: "800 / 1440 / 2592",
      Mana: "150",
      Starting_Mana: "75",
      Armor: "40",
      MR: "40",
      DPS: "39 / 70 / 126",
      Damage: "60 / 108 / 194",
      Atk_Spd: "0.65",
      Crit_Rate: "25%",
      Range: "1",
    },
    skill: {
      name: "Infernal Chains",
      type: "Active",
      des:
        "After a brief delay, Aatrox pulls in the farthest enemies then slams the ground, dealing magic damage to all adjacent enemies.",
      effects: ["Damage: 250 / 450 / 1250", "Number of Enemies: 2 / 2 / 5"],
    },
    origin: [1],
    class: [7],
    items: [37, 22, 52],
    avt: "Aatrox.png",
    imgSkill: "aatrox-infernal-chains.png",
    name: "Aatrox",
    id: 1,
  },
  {
    stat: {
      Cost: "4",
      Health: "600 / 1080 / 1944",
      Mana: "80",
      Armor: "20",
      MR: "20",
      DPS: "30 / 54 / 97",
      Damage: "40 / 72 / 130",
      Atk_Spd: "0.75",
      Crit_Rate: "25%",
      Range: "4",
    },
    skill: {
      name: "Spirit Bomb",
      type: "Active",
      des:
        "Ahri channels, summoning a large ball of spirit energy. After 1.5 seconds, she lobs it at her target dealing magic damage to all enemies within 2 hexes.",
      effects: ["Damage: 500 / 700 / 3000"],
    },
    origin: [12],
    class: [5],
    items: [38, 41, 41],
    avt: "Ahri.png",
    imgSkill: "ahri-spirit-bomb.png",
    name: "Ahri",
    id: 2,
  },
  {
    stat: {
      Cost: "3",
      Health: "650 / 1170 / 2106",
      Mana: "20",
      Armor: "20",
      MR: "20",
      DPS: "47 / 84 / 151",
      Damage: "55 / 99 / 178",
      Atk_Spd: "0.85",
      Crit_Rate: "25%",
      Range: "1",
    },
    skill: {
      name: "Five-Point Strike",
      type: "Active",
      des: "Akali throws kunai at her target, dealing magic damage.",
      effects: ["Damage: 175 / 250 / 400"],
    },
    origin: [5],
    class: [8],
    items: [6, 40, 19],
    avt: "Akali.png",
    imgSkill: "akali-five-point-strike.png",
    name: "Akali",
    id: 3,
  },
  {
    stat: {
      Cost: "2",
      Health: "750 / 1350 / 2430",
      Mana: "65",
      Armor: "40",
      MR: "40",
      DPS: "27 / 49 / 87",
      Damage: "45 / 81 / 146",
      Atk_Spd: "0.6",
      Crit_Rate: "25%",
      Range: "2",
    },
    skill: {
      name: "Shield-Blast",
      type: "Active",
      des:
        "Annie blasts a cone of fire dealing magic damage to enemies in front of her, then creates a shield for herself for a few seconds.",
      effects: ["Damage: 250 / 400 / 600", "Shield amount: 500 / 700 / 900"],
    },
    origin: [4],
    class: [5],
    items: [37, 14, 22],
    avt: "Annie.png",
    imgSkill: "annie-shield-blast.png",
    name: "Annie",
    id: 4,
  },
  {
    stat: {
      Cost: "2",
      Health: "500 / 900 / 1620",
      Mana: "80",
      Starting_Mana: "50",
      Armor: "20",
      MR: "20",
      DPS: "38 / 68 / 122",
      Damage: "50 / 90 / 162",
      Atk_Spd: "0.75",
      Crit_Rate: "25%",
      Range: "4",
    },
    skill: {
      name: "Sentry Turret",
      type: "Active",
      des:
        "Aphelios summons a turret for a few seconds. An extension of his will, the turret counts as Aphelios himself when it fires and deals damage, and dies when he dies.",
      effects: ["Duration: 7 / 8 / 9 / 11"],
    },
    origin: [11],
    class: [4],
    items: [21, 21, 21],
    avt: "Aphelios.png",
    imgSkill: "aphelios-sentry-turret.png",
    name: "Aphelios",
    id: 5,
  },
  {
    stat: {
      Cost: "4",
      Health: "600 / 1080 / 1944",
      Mana: "30",
      Armor: "20",
      MR: "20",
      DPS: "60 / 108 / 194",
      Damage: "80 / 144 / 259",
      Atk_Spd: "0.75",
      Crit_Rate: "25%",
      Range: "4",
    },
    skill: {
      name: "Hunter's Focus",
      type: "Active",
      des:
        "Ashe gains Attack Speed for 5 seconds, and her Basic Attacks fire a flurry of arrows dealing physical damage.",
      effects: [
        "Damage Per Arrow: 45% / 45% / 45%",
        "Attack speed: 45% / 65% / 300%",
      ],
    },
    origin: [9],
    class: [4],
    items: [11, 12, 18],
    avt: "Ashe.png",
    imgSkill: "ashe-hunters-focus.png",
    name: "Ashe",
    id: 6,
  },
  {
    stat: {
      Cost: "5",
      Health: "950 / 1710 / 3078",
      Mana: "150",
      Starting_Mana: "75",
      Armor: "30",
      MR: "20",
      DPS: "60 / 107 / 193",
      Damage: "70 / 126 / 227",
      Atk_Spd: "0.85",
      Crit_Rate: "25%",
      Range: "4",
    },
    skill: {
      name: "Warlord's Divide",
      type: "Active",
      des:
        "Azir charges forward with a wall of soldiers, knocking back enemies hit and dealing magic damage. After their charge, the wall of soldiers remains in place in front of Azir for 3 seconds as impassable terrain. Any spearmen from the General trait will accompany Azir for the charge and position themselves to protect him afterwards.",
      effects: ["Wall Damage: 200 / 350 / 8888"],
    },
    origin: [7],
    class: [10, 11],
    items: [38, 12, 21],
    avt: "Azir.png",
    imgSkill: "azir-warlords-divide.png",
    name: "Azir",
    id: 7,
  },
  {
    stat: {
      Cost: "4",
      Health: "750 / 1350 / 2430",
      Mana: "150",
      Starting_Mana: "80",
      Armor: "30",
      MR: "20",
      DPS: "33 / 59 / 107",
      Damage: "55 / 99 / 178",
      Atk_Spd: "0.6",
      Crit_Rate: "25%",
      Range: "2",
    },
    skill: {
      name: "Petrifying Gaze",
      type: "Active",
      des:
        "Cassiopeia releases a cone of magic energy towards her target, dealing magic damage to all enemies hit, stunning them for a few seconds, and causing them to take 10% increased damage while stunned.",
      effects: [
        "Damage: 275 / 400 / 2000",
        "Stun duration: 2.5 / 3 / 5",
        "Bonus Damage: 20% / 20% / 20%",
      ],
    },
    origin: [2],
    class: [12],
    items: [6, 21, 27],
    avt: "Cassiopeia.png",
    imgSkill: "cassiopeia-petrifying-gaze.png",
    name: "Cassiopeia",
    id: 8,
  },
  {
    stat: {
      Cost: "1",
      Health: "500 / 900 / 1620",
      Mana: "70",
      Armor: "30",
      MR: "20",
      DPS: "33 / 59 / 105",
      Damage: "50 / 90 / 162",
      Atk_Spd: "0.65",
      Crit_Rate: "25%",
      Range: "1",
    },
    skill: {
      name: "Pale Cascade",
      type: "Active",
      des:
        "Diana shields herself for a few seconds and summons orbs to orbit around her. These orbs explode dealing magic damage when they contact an enemy, refreshing her shield when the final one explodes.",
      effects: [
        "Damage: 70 / 80 / 90 / 100",
        "Shield amount: 200 / 300 / 400 / 500",
        "Orbs: 4 / 5 / 6 / 9",
      ],
    },
    origin: [11],
    class: [8],
    items: [13, 18, 50],
    avt: "Diana.png",
    imgSkill: "diana-pale-cascade.png",
    name: "Diana",
    id: 9,
  },
  {
    stat: {
      Cost: "1",
      Health: "600 / 1080 / 1944",
      Mana: "75",
      Armor: "30",
      MR: "20",
      DPS: "29 / 53 / 95",
      Damage: "45 / 81 / 146",
      Atk_Spd: "0.65",
      Crit_Rate: "25%",
      Range: "2",
    },
    skill: {
      name: "Spider Form",
      type: "Active",
      des:
        "Elise transforms into a spider, gaining bonus maximum health and causing her attacks to restore health.",
      effects: [
        "Bonus Health: 35% / 40% / 45%",
        "Health on Hit: 40 / 80 / 160",
      ],
    },
    origin: [1],
    class: [11],
    items: [8, 37, 52],
    avt: "Elise.png",
    imgSkill: "elise-spider-form.png",
    name: "Elise",
    id: 10,
  },
  {
    stat: {
      Cost: "3",
      Health: "600 / 1080 / 1944",
      Mana: "60",
      Armor: "20",
      MR: "20",
      DPS: "49 / 88 / 159",
      Damage: "70 / 126 / 227",
      Atk_Spd: "0.7",
      Crit_Rate: "25%",
      Range: "1",
    },
    skill: {
      name: "Last Caress",
      type: "Active",
      des:
        "Evelynn deals magic damage to up to 3 nearby enemies, then teleports away. The damage is increased against targets below 50% health.",
      effects: ["Damage: 350 / 500 / 1400", "Damage Multiplier: 3 / 3 / 3"],
    },
    origin: [1],
    class: [6],
    items: [38, 13, 14],
    avt: "Evelynn.png",
    imgSkill: "evelynn-last-caress.png",
    name: "Evelynn",
    id: 11,
  },
  {
    stat: {
      Cost: "5",
      Health: "750 / 1350 / 2430",
      Mana: "150",
      Starting_Mana: "90",
      Armor: "20",
      MR: "20",
      DPS: "72 / 130 / 233",
      Damage: "80 / 144 / 259",
      Atk_Spd: "0.9",
      Crit_Rate: "25%",
      Range: "4",
    },
    skill: {
      name: "Trueshot Barrage",
      type: "Active",
      des:
        "Ezreal fires a barrage toward the enemy with the highest Attack Speed, healing allies it passes through and granting them and 50% attack speed for 5 seconds, while dealing magic damage to enemies and slowing their Attack Speed by 50% for 5 seconds.",
      effects: ["Damage: 250 / 450 / 9999", "Healing: 250 / 450 / 9999"],
    },
    origin: [9],
    class: [9],
    items: [12, 44, 21],
    avt: "Ezreal.png",
    imgSkill: "ezreal-trueshot-barrage.png",
    name: "Ezreal",
    id: 12,
  },
  {
    stat: {
      Cost: "1",
      Health: "600 / 1080 / 1944",
      Mana: "85",
      Armor: "35",
      MR: "30",
      DPS: "34 / 61 / 109",
      Damage: "45 / 81 / 146",
      Atk_Spd: "0.75",
      Crit_Rate: "25%",
      Range: "1",
    },
    skill: {
      name: "Riposte",
      type: "Active",
      des:
        "Fiora enters a defensive stance for 1.5 seconds, becoming immune to damage and enemy spell effects. As she exits this stance, she ripostes, dealing magic damage to a nearby enemy and stunning them for a few seconds.",
      effects: ["Damage: 200 / 300 / 450", "Stun duration: 1.5 / 2 / 3"],
    },
    origin: [3],
    class: [3],
    items: [8, 38, 39],
    avt: "Fiora.png",
    imgSkill: "fiora-riposte.png",
    name: "Fiora",
    id: 13,
  },
  {
    stat: {
      Cost: "1",
      Health: "600 / 1080 / 1944",
      Mana: "100",
      Armor: "50",
      MR: "35",
      DPS: "30 / 54 / 97",
      Damage: "50 / 90 / 162",
      Atk_Spd: "0.6",
      Crit_Rate: "25%",
      Range: "1",
    },
    skill: {
      name: "Judgment",
      type: "Active",
      des:
        "Garen spins his sword for 4 seconds, reducing incoming magic damage by 80% and dealing magic damage to nearby enemies over the duration.",
      effects: ["Damage: 450 / 675 / 1125"],
    },
    origin: [7],
    class: [7],
    items: [38, 14, 44],
    avt: "Garen.png",
    imgSkill: "garen-judgment.png",
    name: "Garen",
    id: 14,
  },
  {
    stat: {
      Cost: "2",
      Health: "750 / 1350 / 2430",
      Mana: "120",
      Armor: "45",
      MR: "30",
      DPS: "30 / 54 / 98",
      Damage: "55 / 99 / 178",
      Atk_Spd: "0.55",
      Crit_Rate: "25%",
      Range: "1",
    },
    skill: {
      name: "Spirit of Life",
      type: "Active",
      des: "Hecarim absorbs health from each adjacent enemy over 2 seconds.",
      effects: ["Damage: 250 / 400 / 600", "Healing: 250 / 400 / 600"],
    },
    origin: [9],
    class: [7],
    items: [8, 37, 22],
    avt: "Hecarim.png",
    imgSkill: "hecarim-spirit-of-life.png",
    name: "Hecarim",
    id: 15,
  },
  {
    stat: {
      Cost: "3",
      Health: "800 / 1440 / 2592",
      Mana: "100",
      Starting_Mana: "50",
      Armor: "40",
      MR: "40",
      DPS: "36 / 64 / 116",
      Damage: "55 / 99 / 178",
      Atk_Spd: "0.65",
      Crit_Rate: "25%",
      Range: "1",
    },
    skill: {
      name: "Bladestorm",
      type: "Active",
      des:
        "Irelia launches a barrage of blades infront of her, dealing magic damage and applying on-hit effects. Enemies hit are disarmed for a few seconds.",
      effects: ["Damage: 200 / 300 / 600", "Disarm Duration: 2.5 / 3 / 3.5"],
    },
    origin: [8, 3],
    class: [1],
    items: [8, 38, 39],
    avt: "Irelia.png",
    imgSkill: "irelia-bladestorm.png",
    name: "Irelia",
    id: 16,
  },
  {
    stat: {
      Cost: "2",
      Health: "550 / 990 / 1782",
      Mana: "60",
      Starting_Mana: "30",
      Armor: "20",
      MR: "20",
      DPS: "24 / 43 / 78",
      Damage: "40 / 72 / 130",
      Atk_Spd: "0.6",
      Crit_Rate: "25%",
      Range: "4",
    },
    skill: {
      name: "Eye of the Storm",
      type: "Active",
      des:
        "Janna shields the lowest health allies for 4 seconds. Shielded allies gain Attack Damage for the duration.",
      effects: [
        "Shield amount: 250 / 300 / 400",
        "Number of Allies: 2 / 3 / 4",
        "Bonus Attack Damage: 20 / 30 / 60",
      ],
    },
    origin: [3],
    class: [12],
    items: [6, 21, 27],
    avt: "Janna.png",
    imgSkill: "janna-eye-of-the-storm.png",
    name: "Janna",
    id: 17,
  },
  {
    stat: {
      Cost: "2",
      Health: "600 / 1080 / 1944",
      Mana: "80",
      Starting_Mana: "50",
      Armor: "45",
      MR: "30",
      DPS: "36 / 65 / 117",
      Damage: "60 / 108 / 194",
      Atk_Spd: "0.6",
      Crit_Rate: "25%",
      Range: "1",
    },
    skill: {
      name: "Dragon Strike",
      type: "Active",
      des:
        "Jarvan strikes the furthest target within 3 hexes with his spear and pulls himself towards them, dealing magic damage to units he passes through and knocking them up and stunning them for 1 second.",
      effects: ["Damage: 175 / 250 / 750"],
    },
    origin: [7],
    class: [11],
    items: [38, 14, 44],
    avt: "JarvanIV.png",
    imgSkill: "jarvan-iv-dragon-strike.png",
    name: "Jarvan IV",
    id: 18,
  },
  {
    stat: {
      Cost: "2",
      Health: "750 / 1350 / 2430",
      Mana: "110",
      Starting_Mana: "60",
      Armor: "40",
      MR: "30",
      DPS: "45 / 81 / 146",
      Damage: "60 / 108 / 194",
      Atk_Spd: "0.75",
      Crit_Rate: "25%",
      Range: "1",
    },
    skill: {
      name: "Counter Strike",
      type: "Active",
      des:
        "Jax dodges all incoming attacks for 2 seconds, then strikes all nearby units, dealing magic damage and stunning them for 1.5 seconds.",
      effects: ["Damage: 150 / 250 / 450"],
    },
    origin: [8],
    class: [3],
    items: [8, 37, 22],
    avt: "Jax.png",
    imgSkill: "jax-counter-strike.png",
    name: "Jax",
    id: 19,
  },
  {
    stat: {
      Cost: "4",
      Health: "600 / 1080 / 1944",
      Mana: "0",
      Armor: "20",
      MR: "20",
      DPS: "80 / 144 / 259",
      Damage: "100 / 180 / 324",
      Atk_Spd: "0.8",
      Crit_Rate: "25%",
      Range: "4",
    },
    skill: {
      name: "Whisper",
      type: "Passive",
      des:
        "Passive: Jhin converts each 1% of bonus attack speed he has into 0.8 attack damage. Every fourth shot, Jhin deals bonus damage.",
      effects: [
        "Percent of Attack Damage: 444% / 500% / 1234%",
        "Attacks Per Second: 0.85 / 0.9 / 1.2",
      ],
    },
    origin: [1],
    class: [13],
    items: [38, 40, 15],
    avt: "Jhin.png",
    imgSkill: "jhin-whisper.png",
    name: "Jhin",
    id: 20,
  },
  {
    stat: {
      Cost: "3",
      Health: "650 / 1170 / 2106",
      Mana: "120",
      Starting_Mana: "70",
      Armor: "20",
      MR: "20",
      DPS: "56 / 101 / 182",
      Damage: "75 / 135 / 243",
      Atk_Spd: "0.75",
      Crit_Rate: "25%",
      Range: "4",
    },
    skill: {
      name: "Fishbones",
      type: "Active",
      des:
        "Jinx's next attack fires a rocket, stunning and dealing magic damage to her target and all adjacent enemies.",
      effects: ["Damage: 150 / 250 / 450", "Stun duration: 1.5 / 2 / 2.5"],
    },
    origin: [4],
    class: [13],
    items: [12, 18, 21],
    avt: "Jinx.png",
    imgSkill: "jinx-fishbones.png",
    name: "Jinx",
    id: 21,
  },
  {
    stat: {
      Cost: "3",
      Health: "550 / 990 / 1782",
      Mana: "0",
      Armor: "20",
      MR: "20",
      DPS: "65 / 117 / 211",
      Damage: "65 / 117 / 211",
      Atk_Spd: "1",
      Crit_Rate: "25%",
      Range: "3",
    },
    skill: {
      name: "Rend",
      type: "Passive",
      des:
        "Passive: Kalista's spears remain in her target, each one capable of dealing a percent of the target's max health as magic damage when she removes them. Kalista will remove the spears when doing so would kill the target.",
      effects: ["Maximum Health Damage: 4% / 6% / 9%"],
    },
    origin: [1],
    class: [3],
    items: [12, 19, 20],
    avt: "Kalista.png",
    imgSkill: "kalista-rend.png",
    name: "Kalista",
    id: 22,
  },
  {
    stat: {
      Cost: "3",
      Health: "500 / 900 / 1620",
      Mana: "90",
      Armor: "20",
      MR: "20",
      DPS: "42 / 76 / 137",
      Damage: "65 / 117 / 211",
      Atk_Spd: "0.65",
      Crit_Rate: "25%",
      Range: "1",
    },
    skill: {
      name: "Death Lotus",
      type: "Active",
      des:
        "Katarina channels for 2.5 seconds, throwing knives at nearby enemies, dealing magic damage over the duration and reducing healing by 50% to her targets for 5 seconds.",
      effects: ["Damage: 750 / 900 / 1600", "Number of Targets: 4 / 6 / 8"],
    },
    origin: [4, 7],
    class: [8],
    items: [38, 13, 18],
    avt: "Katarina.png",
    imgSkill: "katarina-death-lotus.png",
    name: "Katarina",
    id: 23,
  },
  {
    stat: {
      Cost: "5",
      Health: "900 / 1620 / 2916",
      Mana: "50",
      Armor: "40",
      MR: "40",
      DPS: "80 / 144 / 259",
      Damage: "80 / 144 / 259",
      Atk_Spd: "1",
      Crit_Rate: "25%",
      Range: "1",
    },
    skill: {
      name: "Reaper",
      type: "Active",
      des:
        "Kayn dashes toward his target then slashes all adjacent enemies, dealing magic damage and increasing the cost of their next spell by 33%. If the slash hits exactly one target, Kayn immediately casts again. As Rhaast: Reaping Slash heals Kayn for 50% of the damage it deals. As Shadow Assassin: Reaping Slash deals an extra 50% damage for the first 10 seconds of combat.",
      effects: ["Damage: 400 / 600 / 6666"],
    },
    origin: [13],
    class: [6],
    items: [8, 38, 45],
    avt: "Kayn.png",
    imgSkill: "kayn-reaper.png",
    name: "Kayn",
    id: 24,
  },
  {
    stat: {
      Cost: "3",
      Health: "650 / 1170 / 2106",
      Mana: "125",
      Starting_Mana: "50",
      Armor: "30",
      MR: "30",
      DPS: "39 / 70 / 126",
      Damage: "60 / 108 / 194",
      Atk_Spd: "0.65",
      Crit_Rate: "25%",
      Range: "2",
    },
    skill: {
      name: "Slicing Maelstrom",
      type: "Active",
      des:
        "Kennen summons a storm around him, dealing magic damage over 3 seconds and stunning enemies inside of it for 1.5 seconds.",
      effects: ["Damage: 300 / 450 / 1200"],
    },
    origin: [5],
    class: [11],
    items: [38, 14, 44],
    avt: "Kennen.png",
    imgSkill: "kennen-slicing-maelstrom.png",
    name: "Kennen",
    id: 25,
  },
  {
    stat: {
      Cost: "3",
      Health: "650 / 1170 / 2106",
      Mana: "35",
      Armor: "20",
      MR: "20",
      DPS: "56 / 101 / 181",
      Damage: "70 / 126 / 227",
      Atk_Spd: "0.8",
      Crit_Rate: "25%",
      Range: "3",
    },
    skill: {
      name: "Dance of Dread",
      type: "Active",
      des:
        "Wolf mauls Kindred's target, dealing magic damage and reducing healing by 50% to her target for 5 seconds, while Lamb leaps away from Kindred's target.",
      effects: ["Damage: 450 / 650 / 1000"],
    },
    origin: [12],
    class: [4],
    items: [6, 40, 41],
    avt: "Kindred.png",
    imgSkill: "kindred-dance-of-dread.png",
    name: "Kindred",
    id: 26,
  },
  {
    stat: {
      Cost: "5",
      Health: "1000 / 1800 / 3240",
      Mana: "40",
      Armor: "50",
      MR: "50",
      DPS: "51 / 92 / 165",
      Damage: "60 / 108 / 194",
      Atk_Spd: "0.85",
      Crit_Rate: "25%",
      Range: "1",
    },
    skill: {
      name: "God Fist",
      type: "Active",
      des:
        "Lee Sin punches his target, dealing magic damage, knocking them back to the edge of the battlefield, and stunning them for a few seconds. Any enemies the target collides with during the knockback receive half the damage and stunned for 1 second. If the target cannot be pushed back any further, they are knocked out of the battlefield instead, removing them from combat. If the target is still alive, Lee Sin will dash to them.",
      effects: ["Damage: 250 / 450 / 1000", "Stun duration: 2 / 3 / 10"],
    },
    origin: [8],
    class: [3],
    items: [8, 37, 38],
    avt: "LeeSin.png",
    imgSkill: "lee-sin-god-fist.png",
    name: "Lee Sin",
    id: 27,
  },
  {
    stat: {
      Cost: "5",
      Health: "950 / 1710 / 3078",
      Mana: "120",
      Starting_Mana: "80",
      Armor: "50",
      MR: "80",
      DPS: "30 / 54 / 97",
      Damage: "40 / 72 / 130",
      Atk_Spd: "0.75",
      Crit_Rate: "25%",
      Range: "2",
    },
    skill: {
      name: "Lilting Lullaby",
      type: "Active",
      des:
        "Lillia casts a magical lullaby, causing waking enemies with the highest current health to fall asleep. Enemies will awaken if they take damage while sleeping, causing an additional magic damage.",
      effects: [
        "Number of Enemies: 2 / 3 / 10",
        "Break Damage: 500 / 500 / 500",
        "Damage: 500 / 750 / 5000",
        "Duration: 2 / 3 / 10",
      ],
    },
    origin: [2],
    class: [5],
    items: [38, 45, 21],
    avt: "Lillia.png",
    imgSkill: "lillia-lilting-lullaby.png",
    name: "Lillia",
    id: 28,
  },
  {
    stat: {
      Cost: "1",
      Health: "550 / 990 / 1782",
      Mana: "50",
      Armor: "20",
      MR: "20",
      DPS: "24 / 43 / 78",
      Damage: "40 / 72 / 130",
      Atk_Spd: "0.6",
      Crit_Rate: "25%",
      Range: "3",
    },
    skill: {
      name: "1000 Daggers",
      type: "Active",
      des:
        "Lissandra hurls a dagger at her target's location, exploding into many daggers on contact with an enemy or when it reaches its destination. The initial dagger deals magic damage, and all enemies hit by the dagger explosion are dealt magic damage.",
      effects: [
        "Initial damage: 350 / 450 / 600 / 800",
        "Secondary damage: 175 / 225 / 300 / 450",
      ],
    },
    origin: [11],
    class: [9],
    items: [13, 44, 21],
    avt: "Lissandra.png",
    imgSkill: "lissandra-1000-daggers.png",
    name: "Lissandra",
    id: 29,
  },
  {
    stat: {
      Cost: "2",
      Health: "500 / 900 / 1620",
      Mana: "120",
      Starting_Mana: "60",
      Armor: "20",
      MR: "20",
      DPS: "30 / 54 / 97",
      Damage: "50 / 90 / 162",
      Atk_Spd: "0.6",
      Crit_Rate: "25%",
      Range: "3",
    },
    skill: {
      name: "Wild Growth",
      type: "Active",
      des:
        "Lulu makes a low health ally giant, granting them bonus health and knocking up adjacent enemies near them for 1 seconds.",
      effects: ["Bonus Health: 400 / 600 / 950"],
    },
    origin: [9],
    class: [5],
    items: [6, 21, 27],
    avt: "Lulu.png",
    imgSkill: "lulu-wild-growth.png",
    name: "Lulu",
    id: 30,
  },
  {
    stat: {
      Cost: "3",
      Health: "600 / 1080 / 1944",
      Mana: "100",
      Starting_Mana: "50",
      Armor: "20",
      MR: "20",
      DPS: "28 / 50 / 91",
      Damage: "40 / 72 / 130",
      Atk_Spd: "0.7",
      Crit_Rate: "25%",
      Range: "4",
    },
    skill: {
      name: "Light Binding",
      type: "Active",
      des:
        "Lux fires a sphere of darkness towards the farthest enemy. Enemies in its path take magic damage and are stunned for a few seconds.",
      effects: ["Damage: 300 / 400 / 700", "Stun duration: 1.5 / 2 / 3"],
    },
    origin: [8],
    class: [9],
    items: [44, 45, 21],
    avt: "Lux.png",
    imgSkill: "lux-light-binding.png",
    name: "Lux",
    id: 31,
  },
  {
    stat: {
      Cost: "1",
      Health: "700 / 1260 / 2268",
      Mana: "75",
      Armor: "35",
      MR: "20",
      DPS: "28 / 50 / 89",
      Damage: "55 / 99 / 178",
      Atk_Spd: "0.5",
      Crit_Rate: "25%",
      Range: "1",
    },
    skill: {
      name: "Bramble Smash",
      type: "Active",
      des:
        "Maokai smashes enemies infront of him, dealing magic damage and slowing their Attack Speed by 50% for 3 seconds.",
      effects: ["Damage: 225 / 350 / 550"],
    },
    origin: [9],
    class: [2],
    items: [8, 37, 52],
    avt: "Maokai.png",
    imgSkill: "maokai-bramble-smash.png",
    name: "Maokai",
    id: 32,
  },
  {
    stat: {
      Cost: "4",
      Health: "750 / 1350 / 2430",
      Mana: "120",
      Starting_Mana: "60",
      Armor: "30",
      MR: "60",
      DPS: "35 / 63 / 113",
      Damage: "50 / 90 / 162",
      Atk_Spd: "0.7",
      Crit_Rate: "25%",
      Range: "3",
    },
    skill: {
      name: "Hallowed Ground",
      type: "Active",
      des:
        "Morgana hallows the ground beneath her target, dealing magic damage to enemies within over 5 seconds and shredding 40% of their Magic Resistance while they remain inside. Morgana restores a percentage of the damage done.",
      effects: ["Damage: 250 / 400 / 2000", "Healing: 20% / 25% / 30%"],
    },
    origin: [3],
    class: [9],
    items: [6, 44, 45],
    avt: "Morgana.png",
    imgSkill: "morgana-hallowed-ground.png",
    name: "Morgana",
    id: 33,
  },
  {
    stat: {
      Cost: "1",
      Health: "550 / 990 / 1782",
      Mana: "100",
      Starting_Mana: "60",
      Armor: "20",
      MR: "20",
      DPS: "26 / 47 / 84",
      Damage: "40 / 72 / 130",
      Atk_Spd: "0.65",
      Crit_Rate: "25%",
      Range: "3",
    },
    skill: {
      name: "Aqua Prison",
      type: "Active",
      des:
        "Nami traps the closest enemy in a bubble, dealing magic damage and stunning them for a few seconds.",
      effects: ["Damage: 225 / 325 / 450", "Stun duration: 2.5 / 3 / 4"],
    },
    origin: [3],
    class: [5],
    items: [16, 16, 18],
    avt: "Nami.png",
    imgSkill: "nami-aqua-prison.png",
    name: "Nami",
    id: 34,
  },
  {
    stat: {
      Cost: "1",
      Health: "550 / 990 / 1782",
      Mana: "80",
      Armor: "30",
      MR: "20",
      DPS: "31 / 57 / 102",
      Damage: "45 / 81 / 146",
      Atk_Spd: "0.7",
      Crit_Rate: "25%",
      Range: "4",
    },
    skill: {
      name: "Javelin Toss",
      type: "Active",
      des:
        "Nidalee throws her Javelin at the furthest enemy, dealing magic damage plus 20% per hex traveled.",
      effects: ["Damage: 225 / 350 / 600"],
    },
    origin: [7],
    class: [13],
    items: [41, 45, 21],
    avt: "Nidalee.png",
    imgSkill: "nidalee-javelin-toss.png",
    name: "Nidalee",
    id: 35,
  },
  {
    stat: {
      Cost: "3",
      Health: "750 / 1350 / 2430",
      Mana: "85",
      Armor: "50",
      MR: "30",
      DPS: "36 / 64 / 116",
      Damage: "65 / 117 / 211",
      Atk_Spd: "0.55",
      Crit_Rate: "25%",
      Range: "1",
    },
    skill: {
      name: "Consume",
      type: "Active",
      des:
        "Willump bites his target, dealing magic damage. If Willump's target has less Health than him before the bite, it deals an additional 50% damage and deals true damage instead.",
      effects: ["Damage: 450 / 650 / 1800"],
    },
    origin: [9],
    class: [2],
    items: [37, 13, 52],
    avt: "Nunu.png",
    imgSkill: "nunu-consume.png",
    name: "Nunu",
    id: 36,
  },
  {
    stat: {
      Cost: "2",
      Health: "700 / 1260 / 2268",
      Mana: "125",
      Starting_Mana: "75",
      Armor: "50",
      MR: "30",
      DPS: "30 / 54 / 97",
      Damage: "50 / 90 / 162",
      Atk_Spd: "0.6",
      Crit_Rate: "25%",
      Range: "1",
    },
    skill: {
      name: "Phantom Undertow",
      type: "Active",
      des:
        "Pyke dashes behind the furthest enemy, creating an afterimage that deals magic damage and stuns enemies it passes through for a few seconds.",
      effects: ["Damage: 125 / 200 / 375", "Stun duration: 2 / 2.5 / 4"],
    },
    origin: [1],
    class: [8],
    items: [6, 44, 21],
    avt: "Pyke.png",
    imgSkill: "pyke-phantom-undertow.png",
    name: "Pyke",
    id: 37,
  },
  {
    stat: {
      Cost: "4",
      Health: "800 / 1440 / 2592",
      Mana: "20",
      Armor: "35",
      MR: "30",
      DPS: "53 / 95 / 170",
      Damage: "70 / 126 / 227",
      Atk_Spd: "0.75",
      Crit_Rate: "25%",
      Range: "1",
    },
    skill: {
      name: "Energy Slash",
      type: "Active",
      des:
        "Riven dashes and shields herself, then slashes forward dealing magic damage to nearby enemies. Every third cast, Riven leaps into the air and launches forward a large wave of energy that deals magic damage.",
      effects: [
        "Damage: 175 / 250 / 750",
        "Wave Damage: 300 / 450 / 1350",
        "Shield amount: 175 / 250 / 750",
      ],
    },
    origin: [2],
    class: [11],
    items: [14, 18, 22],
    avt: "Riven.png",
    imgSkill: "riven-energy-slash.png",
    name: "Riven",
    id: 38,
  },
  {
    stat: {
      Cost: "4",
      Health: "1000 / 1800 / 3240",
      Mana: "150",
      Starting_Mana: "70",
      Armor: "60",
      MR: "40",
      DPS: "25 / 45 / 80",
      Damage: "45 / 81 / 146",
      Atk_Spd: "0.55",
      Crit_Rate: "25%",
      Range: "1",
    },
    skill: {
      name: "Firecracker",
      type: "Active",
      des:
        "Sejuani sets off a giant firecracker. After a short delay, enemies caught within are dealt magic damage and stunned for a few seconds.",
      effects: ["Damage: 100 / 200 / 800", "Stun duration: 2 / 3.5 / 6"],
    },
    origin: [4],
    class: [7],
    items: [37, 14, 22],
    avt: "Sejuani.png",
    imgSkill: "sejuani-firecracker.png",
    name: "Sejuani",
    id: 39,
  },
  {
    stat: {
      Cost: "5",
      Health: "1100 / 1980 / 3564",
      Mana: "175",
      Starting_Mana: "100",
      Armor: "60",
      MR: "30",
      DPS: "45 / 81 / 146",
      Damage: "60 / 108 / 194",
      Atk_Spd: "0.75",
      Crit_Rate: "25%",
      Range: "1",
    },
    skill: {
      name: "Showstopper",
      type: "Active",
      des:
        "Sett grabs his target and slams them forward, dealing a percent of his target's maximum health in magic damage to all enemies in a large area. Enemies further from the epicenter take less damage.",
      effects: [
        "Primary Damage Percentage: 40% / 60% / 400%",
        "Secondary Damage Percentage: 20% / 30% / 200%",
      ],
    },
    origin: [6],
    class: [2],
    items: [14, 41, 22],
    avt: "Sett.png",
    imgSkill: "sett-showstopper.png",
    name: "Sett",
    id: 40,
  },
  {
    stat: {
      Cost: "4",
      Health: "950 / 1710 / 3078",
      Mana: "100",
      Starting_Mana: "50",
      Armor: "60",
      MR: "40",
      DPS: "39 / 70 / 126",
      Damage: "60 / 108 / 194",
      Atk_Spd: "0.65",
      Crit_Rate: "25%",
      Range: "1",
    },
    skill: {
      name: "Shadow Dash",
      type: "Active",
      des:
        "Shen dashes past his target, shielding himself against damage and taunting all adjacent enemies.",
      effects: ["Shield amount: 500 / 800 / 4000", "Duration: 4 / 4 / 8"],
    },
    origin: [5],
    class: [1, 12],
    items: [8, 37, 22],
    avt: "Shen.png",
    imgSkill: "shen-shadow-dash.png",
    name: "Shen",
    id: 41,
  },
  {
    stat: {
      Cost: "2",
      Health: "700 / 1260 / 2268",
      Mana: "60",
      Starting_Mana: "30",
      Armor: "40",
      MR: "80",
      DPS: "42 / 76 / 136",
      Damage: "70 / 126 / 227",
      Atk_Spd: "0.6",
      Crit_Rate: "25%",
      Range: "1",
    },
    skill: {
      name: "Chain Lash",
      type: "Active",
      des:
        "Sylas lashes his chains out in a 3 hex line, dealing magic damage to enemies hit and increasing the cost of their next spell by 33%.",
      effects: ["Damage: 250 / 400 / 600 / 1000"],
    },
    origin: [11],
    class: [2],
    items: [33, 37, 54],
    avt: "Sylas.png",
    imgSkill: "sylas-chain-lash.png",
    name: "Sylas",
    id: 42,
  },
  {
    stat: {
      Cost: "1",
      Health: "700 / 1260 / 2268",
      Mana: "0",
      Armor: "40",
      MR: "30",
      DPS: "43 / 77 / 138",
      Damage: "85 / 153 / 275",
      Atk_Spd: "0.5",
      Crit_Rate: "25%",
      Range: "1",
    },
    skill: {
      name: "Thick Skin",
      type: "Passive",
      des: "Tahm Kench ignores damage from all sources.",
      effects: ["Damage Reduction: 15 / 25 / 75"],
    },
    origin: [4],
    class: [2],
    items: [8, 37, 50],
    avt: "TahmKench.png",
    imgSkill: "tahm-kench-thick-skin.png",
    name: "Tahm Kench",
    id: 43,
  },
  {
    stat: {
      Cost: "4",
      Health: "750 / 1350 / 2430",
      Mana: "40",
      Armor: "30",
      MR: "20",
      DPS: "72 / 130 / 233",
      Damage: "90 / 162 / 292",
      Atk_Spd: "0.8",
      Crit_Rate: "25%",
      Range: "1",
    },
    skill: {
      name: "Truestrike",
      type: "Active",
      des:
        "Talon stabs his target, striking them for a percent of his attack damage. If this kills them, Talon becomes unstoppable and untargetable while he leaps to the enemy with the lowest Armor.",
      effects: ["Damage: 85% / 135% / 400%"],
    },
    origin: [3],
    class: [8],
    items: [11, 38, 40],
    avt: "Talon.png",
    imgSkill: "talon-truestrike.png",
    name: "Talon",
    id: 44,
  },
  {
    stat: {
      Cost: "2",
      Health: "500 / 900 / 1620",
      Mana: "60",
      Armor: "20",
      MR: "20",
      DPS: "39 / 69 / 125",
      Damage: "55 / 99 / 178",
      Atk_Spd: "0.7",
      Crit_Rate: "25%",
      Range: "3",
    },
    skill: {
      name: "Sporecloud Dart",
      type: "Active",
      des:
        "Teemo fires a dart at his target that explodes into a cloud of spores on contact, poisoning nearby enemies. Poisoned enemies take magic damage over a few seconds and are blinded for the duration.",
      effects: [
        "Damage: 300 / 450 / 900",
        "Damage Per Second: 80 / 100 / 133",
        "Duration: 2.5 / 3 / 4.5",
      ],
    },
    origin: [12],
    class: [13],
    items: [12, 44, 21],
    avt: "Teemo.png",
    imgSkill: "teemo-sporecloud-dart.png",
    name: "Teemo",
    id: 45,
  },
  {
    stat: {
      Cost: "2",
      Health: "700 / 1260 / 2268",
      Mana: "100",
      Starting_Mana: "50",
      Armor: "80",
      MR: "20",
      DPS: "33 / 59 / 107",
      Damage: "60 / 108 / 194",
      Atk_Spd: "0.55",
      Crit_Rate: "25%",
      Range: "2",
    },
    skill: {
      name: "Spectral Lantern",
      type: "Active",
      des:
        "Thresh throws his lantern to the lowest-health ally, shielding them and nearby allies against damage for 4 seconds.",
      effects: ["Shield amount: 250 / 450 / 750"],
    },
    origin: [2],
    class: [7],
    items: [8, 37, 22],
    avt: "Thresh.png",
    imgSkill: "thresh-spectral-lantern.png",
    name: "Thresh",
    id: 46,
  },
  {
    stat: {
      Cost: "1",
      Health: "550 / 990 / 1782",
      Mana: "70",
      Armor: "20",
      MR: "20",
      DPS: "29 / 53 / 95",
      Damage: "45 / 81 / 146",
      Atk_Spd: "0.65",
      Crit_Rate: "25%",
      Range: "3",
    },
    skill: {
      name: "Wild Cards",
      type: "Active",
      des:
        "Twisted Fate throws three cards in a cone that deal magic damage to each enemy they pass through.",
      effects: ["Damage: 250 / 350 / 475"],
    },
    origin: [1],
    class: [5],
    items: [6, 40, 41],
    avt: "TwistedFate.png",
    imgSkill: "twisted-fate-wild-cards.png",
    name: "Twisted Fate",
    id: 47,
  },
  {
    stat: {
      Cost: "1",
      Health: "500 / 900 / 1620",
      Mana: "0",
      Armor: "20",
      MR: "20",
      DPS: "36 / 65 / 117",
      Damage: "40 / 72 / 130",
      Atk_Spd: "0.9",
      Crit_Rate: "25%",
      Range: "4",
    },
    skill: {
      name: "Silver Bolts",
      type: "Passive",
      des:
        "Passive: Whenever Vayne Basic Attacks the same target 3 times, she deals bonus true damage.",
      effects: ["Bonus True Damage: 50 / 90 / 140"],
    },
    origin: [2],
    class: [13],
    items: [11, 12, 20],
    avt: "Vayne.png",
    imgSkill: "vayne-silver-bolts.png",
    name: "Vayne",
    id: 48,
  },
  {
    stat: {
      Cost: "3",
      Health: "600 / 1080 / 1944",
      Mana: "45",
      Armor: "20",
      MR: "20",
      DPS: "24 / 43 / 78",
      Damage: "40 / 72 / 130",
      Atk_Spd: "0.6",
      Crit_Rate: "25%",
      Range: "3",
    },
    skill: {
      name: "Butterfly Burst",
      type: "Active",
      des:
        "Veigar blasts the lowest health enemy with a burst of energy, dealing magic damage. If this kills the target, Veigar permanently gains spell power.",
      effects: ["Damage: 450 / 600 / 900", "Spell Power Increase: 1 / 1 / 2"],
    },
    origin: [9],
    class: [5],
    items: [6, 13, 41],
    avt: "Veigar.png",
    imgSkill: "veigar-butterfly-burst.png",
    name: "Veigar",
    id: 49,
  },
  {
    stat: {
      Cost: "2",
      Health: "700 / 1260 / 2268",
      Mana: "60",
      Armor: "40",
      MR: "30",
      DPS: "39 / 70 / 126",
      Damage: "65 / 117 / 211",
      Atk_Spd: "0.6",
      Crit_Rate: "25%",
      Range: "1",
    },
    skill: {
      name: "Denting Blow",
      type: "Active",
      des:
        "Vi's attack blasts through her target, dealing magic damage to all enemies in a cone and reducing their armor for 8 seconds.",
      effects: ["Damage: 250 / 400 / 800", "Armor Reduction: 50% / 75% / 100%"],
    },
    origin: [7],
    class: [2],
    items: [8, 37, 22],
    avt: "Vi.png",
    imgSkill: "vi-denting-blow.png",
    name: "Vi",
    id: 50,
  },
  {
    stat: {
      Cost: "4",
      Health: "950 / 1710 / 3078",
      Mana: "70",
      Armor: "40",
      MR: "40",
      DPS: "68 / 122 / 220",
      Damage: "85 / 153 / 275",
      Atk_Spd: "0.8",
      Crit_Rate: "25%",
      Range: "1",
    },
    skill: {
      name: "Primal Hunger",
      type: "Active",
      des:
        "Warwick gains Attack Speed, Lifesteal, and moves faster for the rest of combat. While in this state, if Warwick scores a takedown he howls, granting himself and all allies who share a trait with him Attack Speed for 3 seconds.",
      effects: [
        "Attack Speed: 135% / 150% / 500%",
        "Lifesteal: 50% / 50% / 200%",
        "Bonus Attack Speed: 60% / 70% / 200%",
      ],
    },
    origin: [8],
    class: [2, 4],
    items: [38, 18, 22],
    avt: "Warwick.png",
    imgSkill: "warwick-primal-hunger.png",
    name: "Warwick",
    id: 51,
  },
  {
    stat: {
      Cost: "1",
      Health: "650 / 1170 / 2106",
      Mana: "50",
      Armor: "40",
      MR: "30",
      DPS: "36 / 64 / 116",
      Damage: "55 / 99 / 178",
      Atk_Spd: "0.65",
      Crit_Rate: "25%",
      Range: "1",
    },
    skill: {
      name: "Crushing Blow",
      type: "Active",
      des:
        "Wukong slams his target with his staff, dealing a percent of his Attack Damage as physical damage and stunning them for a few seconds.",
      effects: [
        "Percent damage: 225% / 250% / 275%",
        "Stun duration: 1.5 / 2 / 3",
      ],
    },
    origin: [8],
    class: [7],
    items: [34, 12, 19],
    avt: "Wukong.png",
    imgSkill: "wukong-crushing-blow.png",
    name: "Wukong",
    id: 52,
  },
  {
    stat: {
      Cost: "3",
      Health: "700 / 1260 / 2268",
      Mana: "60",
      Starting_Mana: "30",
      Armor: "45",
      MR: "30",
      DPS: "52 / 94 / 168",
      Damage: "65 / 117 / 211",
      Atk_Spd: "0.8",
      Crit_Rate: "25%",
      Range: "1",
    },
    skill: {
      name: "Crescent Guard",
      type: "Active",
      des:
        "Xin Zhao sweeps around him, dealing a percent of his Attack Damage to nearby enemies and gaining Armor and Magic Resist for the rest of combat.",
      effects: [
        "Initial damage: 200 / 250 / 350",
        "Basic Attack Damage Increase: 200 / 200 / 200",
      ],
    },
    origin: [7],
    class: [3],
    items: [32, 18, 50],
    avt: "XinZhao.png",
    imgSkill: "xin-zhao-crescent-guard.png",
    name: "Xin Zhao",
    id: 53,
  },
  {
    stat: {
      Cost: "1",
      Health: "550 / 990 / 1782",
      Mana: "45",
      Armor: "30",
      MR: "20",
      DPS: "35 / 63 / 113",
      Damage: "50 / 90 / 162",
      Atk_Spd: "0.7",
      Crit_Rate: "25%",
      Range: "1",
    },
    skill: {
      name: "Striking Steel",
      type: "Active",
      des:
        "Yasuo strikes forward two hexes, dealing a percent of his Attack Damage as physical damage and applying on-hit effects.",
      effects: ["Percent of Attack Damage: 180% / 200% / 225%"],
    },
    origin: [10],
    class: [3],
    items: [38, 39, 18],
    avt: "Yasuo.png",
    imgSkill: "yasuo-striking-steel.png",
    name: "Yasuo",
    id: 54,
  },
  {
    stat: {
      Cost: "5",
      Health: "950 / 1710 / 3078",
      Mana: "50",
      Armor: "40",
      MR: "40",
      DPS: "76 / 137 / 246",
      Damage: "80 / 144 / 259",
      Atk_Spd: "0.95",
      Crit_Rate: "25%",
      Range: "1",
    },
    skill: {
      name: "Seal Fate",
      type: "Active",
      des:
        "Yone strikes along a path in front of him, dealing magic damage split between all enemies hit. Enemies hit are marked for death, reducing their Armor and Magic Resist by 90%. Yone's spell is then replaced with Unforgotten until there are no remaining enemies marked for death. Unforgotten (20 mana): Yone dashes to the lowest health enemy that is marked for death, killing them instantly.",
      effects: [
        "Damage: 600 / 1200 / 9999",
        "Unforgotten Base Damage: 200 / 400 / 1000",
      ],
    },
    origin: [10],
    class: [1],
    items: [38, 39, 18],
    avt: "Yone.png",
    imgSkill: "yone-seal-fate.png",
    name: "Yone",
    id: 55,
  },
  {
    stat: {
      Cost: "3",
      Health: "600 / 1080 / 1944",
      Mana: "40",
      Armor: "20",
      MR: "20",
      DPS: "24 / 43 / 78",
      Damage: "40 / 72 / 130",
      Atk_Spd: "0.6",
      Crit_Rate: "25%",
      Range: "3",
    },
    skill: {
      name: "Zoomies",
      type: "Active",
      des:
        "Yuumi dashes next to a low health ally, healing them for a percent of their missing health and granting them attack speed for 5 seconds. She then repeats this for the furthest ally.",
      effects: ["Healing: 30% / 45% / 75%", "Attack Speed: 30% / 40% / 60%"],
    },
    origin: [12],
    class: [12],
    items: [6, 21, 27],
    avt: "Yuumi.png",
    imgSkill: "yuumi-zoomies.png",
    name: "Yuumi",
    id: 56,
  },
  {
    stat: {
      Cost: "2",
      Health: "600 / 1080 / 1944",
      Mana: "0",
      Armor: "20",
      MR: "20",
      DPS: "44 / 79 / 143",
      Damage: "55 / 99 / 178",
      Atk_Spd: "0.8",
      Crit_Rate: "25%",
      Range: "1",
    },
    skill: {
      name: "Contempt for the Weak",
      type: "Passive",
      des:
        "Passive: Every third attack, Zed deals bonus magic damage and steals a percent of the target's current Attack Damage.",
      effects: [
        "Damage: 40 / 50 / 75",
        "Attack Damage Stolen: 30% / 35% / 40%",
      ],
    },
    origin: [5],
    class: [6],
    items: [12, 18, 19],
    avt: "Zed.png",
    imgSkill: "zed-contempt-for-the-weak.png",
    name: "Zed",
    id: 57,
  },
  {
    stat: {
      Cost: "5",
      Health: "750 / 1350 / 2430",
      Mana: "150",
      Starting_Mana: "100",
      Armor: "20",
      MR: "20",
      DPS: "34 / 61 / 109",
      Damage: "45 / 81 / 146",
      Atk_Spd: "0.75",
      Crit_Rate: "25%",
      Range: "3",
    },
    skill: {
      name: "Rewind Fate",
      type: "Active",
      des:
        "Zilean places a protective Time Rune on the 2 allies with the lowest Health. When they would die, they instead resurrect after 3.5 seconds, returning to combat with some health and shredding all negative effects. After resurrecting, they have 50% bonus Attack Speed for the rest of combat.",
      effects: [
        "Number of Allies: 2 / 3 / 10",
        "Revive Delay: 3.5 / 3 / 1",
        "Health Restored: 350 / 500 / 3000",
      ],
    },
    origin: [1],
    class: [12],
    items: [6, 38, 21],
    avt: "Zilean.png",
    imgSkill: "zilean-rewind-fate.png",
    name: "Zilean",
    id: 58,
  },
];
