export const classesUnit = [
  {
    name: "Adept",
    units: [16, 41, 55],
    icon: "adept.png",
    desc:
      "Adepts calm the flow of battle, reducing the Attack Speed of all enemies by 50% for a few seconds at the start of combat.",
    active: ["2", "3", "4"],
    effect: ["2 Seconds", "3.5 Seconds", "6 Seconds"],
    id: 1,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    effect_vi: "Chưa dịch",
    search_text: "",
  },
  {
    name: "Brawler",
    units: [32, 36, 40, 42, 43, 50, 51],
    icon: "brawler.png",
    desc: "Brawlers gain bonus Maximum Health.",
    active: ["2", "4", "6", "8"],
    effect: [
      "400 Bonus Health",
      "800 Bonus Health",
      "1200 Bonus Health",
      "1800 Bonus Health",
    ],
    id: 2,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    effect_vi: "Chưa dịch",
    search_text: "",
  },
  {
    name: "Duelist",
    units: [13, 19, 22, 27, 53, 54],
    icon: "duelist.png",
    desc:
      "Innate: Duelists gain bonus Movement Speed.\nDuelists' attacks grant Attack Speed, up to 8 stacks.",
    active: ["2", "4", "6", "8"],
    effect: [
      "12% Attack Speed per Stack",
      "20% Attack Speed per Stack",
      "35% Attack Speed per Stack",
      "60% Attack Speed per Stack",
    ],
    id: 3,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    effect_vi: "Chưa dịch",
    search_text: "",
  },
  {
    name: "Hunter",
    units: [5, 6, 26, 51],
    icon: "hunter.png",
    desc:
      "Every few seconds, all Hunters will attack the lowest percent Health enemy, dealing bonus damage.",
    active: ["2", "3", "4", "5"],
    effect: [
      "125% Bonus Damage every 3.5 seconds",
      "150% Bonus Damage every 3 seconds",
      "175% Bonus Damage every 2.5 seconds",
      "200% Bonus Damage every 2 seconds",
    ],
    id: 4,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    effect_vi: "Chưa dịch",
    search_text: "",
  },
  {
    name: "Mage",
    units: [2, 4, 28, 30, 34, 47, 49],
    icon: "mage.png",
    desc: "Mages cast twice and have modified Spell Power.",
    active: ["3", "6", "9"],
    effect: [
      "80% of their total Spell Power",
      "110% of their total Spell Power",
      "180% of their total Spell Power",
    ],
    id: 5,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    effect_vi: "Chưa dịch",
    search_text: "",
  },
  {
    name: "Shade",
    units: [11, 24, 57],
    icon: "shade.png",
    desc:
      "Innate: When combat starts, Shades teleport to the enemy backline.\nAfter every third attack Shades dip into the shadows, stealthing and causing their next basic attack to deal bonus magic damage.",
    active: ["2", "3", "4"],
    effect: [
      "125 Bonus Magic Damage",
      "400 Bonus Magic Damage",
      "750 Bonus Magic Damage",
    ],
    id: 6,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    effect_vi: "Chưa dịch",
    search_text: "",
  },
  {
    name: "Vanguard",
    units: [1, 14, 15, 39, 46, 52],
    icon: "vanguard.png",
    desc: "Vanguard champions gain bonus Armor.",
    active: ["2", "4", "6", "8"],
    effect: ["100 Armor", "250 Armor", "600 Armor", "1500 Armor"],
    id: 7,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    effect_vi: "Chưa dịch",
    search_text: "",
  },
  {
    name: "Assassin",
    units: [3, 9, 23, 37, 44],
    icon: "assassin.png",
    desc:
      "Innate: Before combat starts, Assassins leap to the enemy backline.\nAssassins' spells can critically stike and they gain bonus Critical Strike Damage and Chance.",
    active: ["2", "4", "6"],
    effect: [
      "10% Crit Chance and 30% Crit Damage",
      "25% Crit Chance and 60% Crit Damage",
      "40% Crit Chance and 90% Crit Damage",
    ],
    id: 8,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    effect_vi: "Chưa dịch",
    search_text: "",
  },
  {
    name: "Dazzler",
    units: [12, 29, 31, 33],
    icon: "dazzler.png",
    desc: "Dazzler's spells reduce their target's Attack Damage for 8 seconds.",
    active: ["2", "4"],
    effect: ["40% Attack Damage Reduction", "80% Attack Damage Reduction"],
    id: 9,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    effect_vi: "Chưa dịch",
    search_text: "",
  },
  {
    name: "Emperor",
    units: [7],
    icon: "emperor.png",
    desc: "",
    active: ["1"],
    effect: [
      "The Emperor deploys with two Sand Guards who can be placed anywhere on the battlefield. They do not move or attack, and die when their Emperor does.",
    ],
    id: 10,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    effect_vi: "Chưa dịch",
    search_text: "",
  },
  {
    name: "Keeper",
    units: [7, 10, 18, 25, 38],
    icon: "keeper.png",
    desc:
      "At the start of combat, Keepers grant themselves and all nearby allies a shield. This shield is 50% stronger on Keepers.",
    active: ["2", "4", "6"],
    effect: [
      "150 Shield Amount for 8 seconds",
      "225 Shield Amount for 10 seconds",
      "350 Shield Amount for 12 seconds",
    ],
    id: 11,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    effect_vi: "Chưa dịch",
    search_text: "",
  },
  {
    name: "Mystic",
    units: [8, 17, 41, 56, 58],
    icon: "mystic.png",
    desc: "All allies gain Magic Resistance.",
    active: ["2", "4", "6"],
    effect: [
      "40 Magic Resistance",
      "100 Magic Resistance",
      "200 Magic Resistance",
    ],
    id: 12,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    effect_vi: "Chưa dịch",
    search_text: "",
  },
  {
    name: "Sharpshooter",
    units: [20, 21, 35, 45, 48],
    icon: "sharpshooter.png",
    desc:
      "Sharpshooters attacks and spells ricochet to nearby enemies dealing reduced damage.",
    active: ["2", "4", "6"],
    effect: [
      "1 Ricochet with 55% Reduced Damage",
      "2 Ricochets with 50% Reduced Damage",
      "3 Ricochets with 45% Reduced Damage",
    ],
    id: 13,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    effect_vi: "Chưa dịch",
    search_text: "",
  },
];
