export const data_item = [
  {
    desc: "15 Attack damage.",
    name: "B.F. Sword",
    icon: "BFSword.png",
    type: "base",
    citem: [32, 11, 38, 13, 40, 34, 21, 49, 53],
    id: 1,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc: "200 Health.",
    name: "Giant's Belt",
    icon: "GiantsBelt.png",
    type: "base",
    citem: [44, 46, 22, 24, 25, 52, 53, 27, 54],
    id: 2,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc: "25 Magic resist.",
    name: "Negatron Cloak",
    icon: "NegatronCloak.png",
    type: "base",
    citem: [32, 7, 8, 9, 37, 14, 18, 20, 27],
    id: 3,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc: "10% Crit and +10% Dodge chance.",
    name: "Sparring Gloves",
    icon: "SparringGloves.png",
    type: "base",
    citem: [39, 40, 41, 15, 18, 47, 23, 24, 26],
    id: 4,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc: "15 Mana.",
    name: "Tear of the Goddess",
    icon: "TearoftheGoddess.png",
    type: "base",
    citem: [6, 7, 10, 39, 16, 43, 46, 21, 48],
    id: 5,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc: "[Unique] After casting a spell, set your mana to 20.",
    name: "Blue Buff",
    icon: "BlueBuff.png",
    type: "combinedItem",
    bitem: [5, 5],
    id: 6,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc:
      "When combat begins, the wearer and all allies within 1 hex in the same row gain 35 Spell Power for the rest of combat.",
    name: "Chalice of Power",
    icon: "ChaliceofPower.png",
    type: "combinedItem",
    bitem: [3, 5],
    id: 7,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc: "Reduces incoming magic damage by 60%.",
    name: "Dragon's Claw",
    icon: "DragonsClaw.png",
    type: "combinedItem",
    bitem: [3, 3],
    id: 8,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc: "[Unique] The holder gains the Elderwood trait.",
    name: "Elderwood Heirloom",
    icon: "ElderwoodHeirloom.png",
    type: "combinedItem",
    bitem: [31, 3],
    id: 9,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc:
      "Reduces the Attack Speed of nearby enemies by 50%. Each Frozen Heart a champion carries beyond the first increases the radius of this effect.",
    name: "Frozen Heart",
    icon: "FrozenHeart.png",
    type: "combinedItem",
    bitem: [28, 5],
    id: 10,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc:
      "The holder's spells and basic attacks do 10% bonus damage. If the target has more than 1750 maximum Health, the bonus increases to 90%.",
    name: "Giant Slayer",
    icon: "GiantSlayer.png",
    type: "combinedItem",
    bitem: [1, 30],
    id: 11,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc:
      "Basic Attacks grant +6% bonus Attack Speed for the rest of combat. This effect can stack any number of times.",
    name: "Guinsoo's Rageblade",
    icon: "GuinsoosRageblade.png",
    type: "combinedItem",
    bitem: [29, 30],
    id: 12,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc:
      "The holder's spells heal them for 33% of the damage dealt. Excess healing fuels a shield that protects the holder against up to 400 damage.",
    name: "Hextech Gunblade",
    icon: "HextechGunblade.png",
    type: "combinedItem",
    bitem: [1, 29],
    id: 13,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc:
      "Enemies within 2 hexes have their Magic Resist reduced by 40% (does not stack). When they cast a spell, they are zapped taking magic damage equal to 225% of their max Mana.",
    name: "Ionic Spark",
    icon: "IonicSpark.png",
    type: "combinedItem",
    bitem: [29, 3],
    id: 14,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc:
      "[Unique] When the wearer inflicts a critical hit, the target's Armor is reduced by 75% for 3 seconds. This effect does not stack.",
    name: "Last Whisper",
    icon: "LastWhisper.png",
    type: "combinedItem",
    bitem: [30, 4],
    id: 15,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc:
      "When the holder casts their spell, the first target dealt magic damage and up to 3 nearby enemies are dealt an additional 180 magic damage, and 180 bonus damage if they are crowd-controlled.",
    name: "Luden's Echo",
    icon: "LudensEcho.png",
    type: "combinedItem",
    bitem: [29, 5],
    id: 16,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc: "[Unique] The holder gains the Dusk trait.",
    name: "Mantle of Dusk",
    icon: "MantleofDusk.png",
    type: "combinedItem",
    bitem: [31, 29],
    id: 17,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc:
      "[Unique] The wearer is immune to crowd control for the first 10 seconds of combat.",
    name: "Quicksilver",
    icon: "Quicksilver.png",
    type: "combinedItem",
    bitem: [3, 4],
    id: 18,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc:
      "The holder gains 200% Attack Range, and their Basic Attacks can't miss.",
    name: "Rapid Firecannon",
    icon: "RapidFirecannon.png",
    type: "combinedItem",
    bitem: [30, 30],
    id: 19,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc:
      "Basic Attacks fire a bolt at another nearby enemy, dealing 90% of the wearer's Attack Damage and applying on-hit effects. These bolts can critically strike.",
    name: "Runaan's Hurricane",
    icon: "RunaansHurricane.png",
    type: "combinedItem",
    bitem: [3, 30],
    id: 20,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc: "The holder's basic attacks restore 5 Mana on-hit.",
    name: "Spear of Shojin",
    icon: "SpearofShojin.png",
    type: "combinedItem",
    bitem: [1, 5],
    id: 21,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc:
      "[Unique] At start of combat, and every 2 seconds thereafter, a random enemy within 2 hexes is burned for 25% of their maximum health over 10 seconds. Any healing they receive is reduced by 50%.",
    name: "Sunfire Cape",
    icon: "SunfireCape.png",
    type: "combinedItem",
    bitem: [28, 2],
    id: 22,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc:
      "Each planning phase, fetch two temporary items, quality based upon your player level. Consumes three item slots.",
    name: "Thief's Gloves",
    icon: "ThiefsGloves.png",
    type: "combinedItem",
    bitem: [4, 4],
    id: 23,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc:
      "Blocks the first enemy spell that hits the wearer, and stuns the spell's caster for 4 seconds.",
    name: "Trap Claw",
    icon: "TrapClaw.png",
    type: "combinedItem",
    bitem: [2, 4],
    id: 24,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc: "[Unique] The holder gains the Warlord trait.",
    name: "Warlord's Banner",
    icon: "WarlordsBanner.png",
    type: "combinedItem",
    bitem: [31, 2],
    id: 25,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc: "[Unique] The holder gains the Assassin trait.",
    name: "Youmuu's Ghostblade",
    icon: "YoumuusGhostblade.png",
    type: "combinedItem",
    bitem: [31, 4],
    id: 26,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc:
      "[Unique] When combat begins, the wearer summons a whirlwind on the opposite side of the arena that removes the closest enemy from combat for 5 seconds.",
    name: "Zephyr",
    icon: "Zephyr.png",
    type: "combinedItem",
    bitem: [2, 3],
    id: 27,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc: "25 Armor.",
    name: "Chain Vest",
    icon: "ChainVest.png",
    type: "base",
    citem: [33, 10, 37, 38, 42, 47, 22, 50, 51],
    id: 28,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc: "15 Spell power.",
    name: "Needlessly Large Rod",
    icon: "NeedlesslyLargeRod.png",
    type: "base",
    citem: [12, 13, 14, 41, 42, 16, 17, 44, 45],
    id: 29,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc: "20% Attack speed.",
    name: "Recurve Bow",
    icon: "RecurveBow.png",
    type: "base",
    citem: [35, 11, 12, 15, 19, 20, 48, 50, 54],
    id: 30,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc: "It must do something...",
    name: "Spatula",
    icon: "Spatula.png",
    type: "base",
    citem: [35, 9, 36, 43, 17, 49, 51, 25, 26],
    id: 31,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc: "Basic Attacks heal the holder for 40% of the damage dealt.",
    name: "Bloodthirster",
    icon: "Bloodthirster.png",
    type: "combinedItem",
    bitem: [1, 3],
    id: 32,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc:
      "Negates bonus damage from incoming critical hits. On being hit by a Basic Attack, deal 80/100/150★ magic damage to all nearby enemies.",
    name: "Bramble Vest",
    icon: "BrambleVest.png",
    type: "combinedItem",
    bitem: [28, 28],
    id: 33,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc:
      "Contributing to a kill grants the holder +20 Attack Damage for the remainder of combat. This effect can stack any number of times (starting at 1).",
    name: "Deathblade",
    icon: "Deathblade.png",
    type: "combinedItem",
    bitem: [1, 1],
    id: 34,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc: "[Unique] The holder gains the Duelist trait.",
    name: "Duelist's Zeal",
    icon: "DuelistsZeal.png",
    type: "combinedItem",
    bitem: [31, 30],
    id: 35,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc: "Wearer's team gains +1 maximum team size.",
    name: "Force of Nature",
    icon: "ForceofNature.png",
    type: "combinedItem",
    bitem: [31, 31],
    id: 36,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc:
      "The holder gains 15 Armor and 15 Magic Resist for each enemy targeting them.",
    name: "Gargoyle Stoneplate",
    icon: "GargoyleStoneplate.png",
    type: "combinedItem",
    bitem: [28, 3],
    id: 37,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc:
      "Prevents the wearer's first death, placing them in stasis instead. After 2 seconds, they return with 400 Health and shed all negative effects.",
    name: "Guardian Angel",
    icon: "GuardianAngel.png",
    type: "combinedItem",
    bitem: [1, 28],
    id: 38,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc:
      "At the beginning of each planning phase, the wearer gains one of the following: Basic attacks and spells deal +45% Damage or Basic attacks and spells heal for 45% of damage dealt.",
    name: "Hand of Justice",
    icon: "HandofJustice.png",
    type: "combinedItem",
    bitem: [5, 4],
    id: 39,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc:
      "[Unique] Grants 75% Critical Strike Chance (including components). Each point of Critical Strike Chance above 100% become +1% Critical Strike Damage.",
    name: "Infinity Edge",
    icon: "InfinityEdge.png",
    type: "combinedItem",
    bitem: [1, 4],
    id: 40,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc:
      "The holder's spells can inflict critical hits. Gain 40% Critical Strike Damage.",
    name: "Jeweled Gauntlet",
    icon: "JeweledGauntlet.png",
    type: "combinedItem",
    bitem: [29, 4],
    id: 41,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc:
      "When combat begins, the wearer and all allies within 2 hexes in the same row gain a shield that blocks 300/375/500/800★ damage for 8 seconds.",
    name: "Locket of the Iron Solari",
    icon: "LocketoftheIronSolari.png",
    type: "combinedItem",
    bitem: [28, 29],
    id: 42,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc: "[Unique] The holder gains the Mage trait.",
    name: "Mage's Cap",
    icon: "MagesCap.png",
    type: "combinedItem",
    bitem: [31, 5],
    id: 43,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc:
      "[Unique] When the holder deals damage with their spell, they burn the target, dealing 25% of the target's maximum Health as true damage over 10 seconds and reducing healing by 50% for the duration of the burn.",
    name: "Morellonomicon",
    icon: "Morellonomicon.png",
    type: "combinedItem",
    bitem: [2, 29],
    id: 44,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc: "The holder gains 50 additional Spell Power.",
    name: "Rabadon's Deathcap",
    icon: "RabadonsDeathcap.png",
    type: "combinedItem",
    bitem: [29, 29],
    id: 45,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc: "When the wearer dies, allies are healed for 800 Health.",
    name: "Redemption",
    icon: "Redemption.png",
    type: "combinedItem",
    bitem: [2, 5],
    id: 46,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc:
      "[Unique] When combat begins, shoots a beam straight ahead that delays affected enemies' first spellcast, increasing their max Mana by 33% until they cast.",
    name: "Shroud of Stillness",
    icon: "ShroudofStillness.png",
    type: "combinedItem",
    bitem: [28, 4],
    id: 47,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc:
      "Every third Basic Attack from the wearer deals 80 magic damage to 3/4/5/6★ enemies, and 240 true damage if they are shielded.",
    name: "Statikk Shiv",
    icon: "StatikkShiv.png",
    type: "combinedItem",
    bitem: [30, 5],
    id: 48,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc: "[Unique] The holder gains the Divine trait.",
    name: "Sword of the Divine",
    icon: "SwordoftheDivine.png",
    type: "combinedItem",
    bitem: [31, 1],
    id: 49,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc:
      "When the wearer takes damage or inflicts a critical hit, they gain a 1% stacking damage bonus. Stacks up to 25 times, at which point the wearer gains 25 Armor and Magic Resistance, and increases in size.",
    name: "Titan's Resolve",
    icon: "TitansResolve.png",
    type: "combinedItem",
    bitem: [28, 30],
    id: 50,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc: "[Unique] The holder gains the Vanguard trait.",
    name: "Vanguard's Cuirass",
    icon: "VanguardsCuirass.png",
    type: "combinedItem",
    bitem: [31, 28],
    id: 51,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc: "Grants 1000 bonus Health (including components).",
    name: "Warmog's Armor",
    icon: "WarmogsArmor.png",
    type: "combinedItem",
    bitem: [2, 2],
    id: 52,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc:
      "When combat begins, the wearer and all allies within 1 hexes in the same row gain 35% bonus Attack Speed for the rest of combat.",
    name: "Zeke's Herald",
    icon: "ZekesHerald.png",
    type: "combinedItem",
    bitem: [1, 2],
    id: 53,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
  {
    desc:
      "At the start of combat, the wearer taunts all nearby enemies for 1 second. When the wearer dies, a Construct with 1500/2250/3000★ Health arises to continue the fight.",
    name: "Zz'Rot Portal",
    icon: "ZzRotPortal.png",
    type: "combinedItem",
    bitem: [2, 30],
    id: 54,
    name_vi: "Chưa dịch",
    desc_vi: "Chưa dịch",
    stats: {},
    search_text: "",
  },
];
