name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: npm install
      - name: Build
        run: npm run build
        env:
          CI: false
      # - name: Build and Deploy
      #   uses: JamesIves/github-pages-deploy-action@releases/v3
      #   with:
      #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #     BASE_BRANCH: master
      #     BRANCH: gh-pages
      #     FOLDER: build
